### ISSUE TITLE
Question about _pickle.UnpicklingError

### ISSUE THREAD

**Issue by RCLaplace** [ChiSu001/SAT-HMR#4]
Traceback (most recent call last):
  File "/workspace/hmr/main.py", line 5, in <module>
    from engines.engine import Engine
  File "/workspace/hmr/engines/engine.py", line 5, in <module>
    from datasets.multiple_datasets import MultipleDatasets, datasets_dict
  File "/workspace/hmr/datasets/multiple_datasets.py", line 4, in <module>
    from .agora import AGORA
  File "/workspace/hmr/datasets/agora.py", line 8, in <module>
    from .base import BASE
  File "/workspace/hmr/datasets/base.py", line 20, in <module>
    from models.human_models import SMPL_Layer, smpl_gendered
  File "/workspace/hmr/models/__init__.py", line 14, in <module>
    from .sat_model import build_sat_model
  File "/workspace/hmr/models/sat_model.py", line 34, in <module>
    from models.human_models import SMPL_Layer
  File "/workspace/hmr/models/human_models/__init__.py", line 1, in <module>
    from .smpl_models import SMPL_Layer, smpl_gendered
  File "/workspace/hmr/models/human_models/smpl_models.py", line 69, in <module>
    smpl_gendered = SMPL_Layer(smpl_model_path, with_genders = True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/hmr/models/human_models/smpl_models.py", line 21, in __init__
    self.layer_n = smplx.create(model_path, 'smpl', gender='neutral', **smpl_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/sathmr/lib/python3.11/site-packages/smplx/body_models.py", line 2400, in create
    return SMPL(model_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/sathmr/lib/python3.11/site-packages/smplx/body_models.py", line 137, in __init__
    data_struct = Struct(**pickle.load(smpl_file,
                           ^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by ChiSu001** [comment]
Hi @RCLaplace , thanks for your interest in SAT-HMR! 

I haven't encountered this specific issue before, so I'm not sure of the exact solution. Maybe you can check your SMPL files and make sure that they are downloaded completely and correctly. If the problem persists, try to reinstall the environment.

**Comment by RCLaplace** [comment]
> Hi @RCLaplace , thanks for your interest in SAT-HMR!
> 
> I haven't encountered this specific issue before, so I'm not sure of the exact solution. Maybe you can check your SMPL files and make sure that they are downloaded completely and correctly. If the problem persists, try to reinstall the environment.

I tried to reinstall the environment but the problem still occurred. I ran the program in docker.
![企业微信截图_17355396492208](https://github.com/user-attachments/assets/be8bd4e0-318b-431c-92e3-90bd26adeb55)

**Comment by qinwenshuo** [comment]
The issue is with the SMPL pkl file, try re-downloading the SMPL pkl file
